### ISSUE TITLE
Images for past committee members

### ISSUE THREAD

**Issue by neanias** [compsoc-edinburgh/comp-soc.com#3]
Not an "issue" per se, but more of a knowledge transfer: there are images for past committee members are in the https://github.com/compsoc-edinburgh/website repo which you can likely copy over.

Also, how come the website is being rewritten again again again?

**Comment by tomasmaillo** [comment]
Thanks for the heads-up! We've actually already used that repo to copy over all the meeting minutes and team details (pictures, links, names, etc.). Nevertheless, we are on the lookout for lists of even older committee members and would appreciate it if you knew where we could find those.

> Also, how come the website is being rewritten again again again?

That's a very good question haha. I think there are several reasons:

1. Evolving Needs: CompSoc changes over time, and the website should reflect those changes. Eg: the push for more in-person events means the website needs to showcase more event pictures for freshers.
2. Sponsorship Appeal: Sponsors do check our website as a factor in deciding whether to sponsor us. A sleek and modern website can inspire confidence and highlight our members' talents.
3. Modern Tech Stack: Rewriting the website with contemporary technology ensures we can build cooler experiences and that CompSoc members will find the tech stack more familiar.
4. Would we really be a tech-related society if we didn't reinvent the wheel every couple of years?

**Comment by neanias** [comment]
Your best bet is asking the older members of the Discord, I'd think, for finding old committees. #tardis may be a good bet too.

I'd argue that the current/most-recent website _is_ a modern tech stack; it's just a bit simpler/lower maintenance than a Next.js website. <old-man-moment>Back in my day, TechSecs had a habit of running on the platform that the website is rubbish and needs to be rewritten.</old-man-moment> Finally, one TechSec (I forget who) said, 'enough is enough, let's just make a static Jekyll website that does the job and we can stop rewriting it every year!' So that's what we did and we formed SIGWeb to handle stewardship which is roughly where we are now.

The lesson here is "don't rewrite it because you can".

**Comment by tomasmaillo** [comment]
Oh amazing! Thanks

Yeah Jekyll do be simpler! I really loved how easy it is to just add and remove content :) I tried to replicate this as much as possible on the new website. 

I do think that NextJS being more modern, popular and in-demand would be beneficial for any CompSoc member wanting to contribute + companies looking for societies to sponsor. This setup also allows us to do more fun interactions and quicker iterations (like the SIG cards!). The Tech Sec and I picked NextJS because we thought it is the best tool for the project. 

I am very appreciative of what SIGWeb has done with Discord integrations and internal wikis in the past! Very cool stuff. 

While I very much agree with the whole idea of not touching some code if its working, I would say, just in this case: why not? The SIGs are keen to get better exposure to freshers, our president believes a more professional and sleek look would impress sponsors, the committee agreed that the website needed a facelift and the Tech Sec and I want to get experience with new tech! Things might break, but its low stakes (except Aug+Sept), making a website is part of the fun and it plays to our strengths as a tech society!

So, I'd argue that "lesson" doesn't apply here. I'm actually looking forward to seeing whatever CompSoc's website is written in in 2030!

**Comment by neanias** [comment]
Sorry if my message came across as condemning your actions! I'm not anti-rebuild. My only words of wisdom would be to encourage lots of contributors and some stewardship greater than 2 people as the loss of knowledge as people leave the society/graduate can be a killer for existing websites. It happened to us in the past more than once!

**Comment by tomasmaillo** [comment]
Absolutely! Thanks again for all your suggestions ❤️

**Comment by tomasmaillo** [comment]
I'll close this now as the issue on missing images has been resolved
